basePath: /api
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a log analysis API for managing and analyzing logs from various
    servers and environments.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Log Analysis API
  version: "1.0"
paths: {}
schemes:
- http
securityDefinitions:
  BearerAuth:
    description: Bearer token for authentication (e.g., "Bearer your-jwt-token")
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
